server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn_1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  application:
    name: microcloud-provider-dept   #集群配置中所有的服务名称一样
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gwolf.vo
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://microcloud:microcloud@eureka-7001.com:7001/eureka/,http://microcloud:microcloud@eureka-7002.com:7002/eureka/,http://microcloud:microcloud@eureka-7003.com:7003/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true
info:
  app.name: microcloud
  company.name: www.gwolf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$